// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: categoryImages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategoryImage = `-- name: CreateCategoryImage :one
INSERT INTO categories_images (
    category_id,
    image
) VALUES (
    $1,
    $2
) RETURNING id
`

type CreateCategoryImageParams struct {
	CategoryID int32       `json:"category_id"`
	Image      pgtype.Text `json:"image"`
}

func (q *Queries) CreateCategoryImage(ctx context.Context, arg CreateCategoryImageParams) (int32, error) {
	row := q.db.QueryRow(ctx, createCategoryImage, arg.CategoryID, arg.Image)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteCategoryImage = `-- name: DeleteCategoryImage :one
DELETE FROM categories_images WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteCategoryImage(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, deleteCategoryImage, id)
	err := row.Scan(&id)
	return id, err
}

const getAllCategoryImages = `-- name: GetAllCategoryImages :many
SELECT id, category_id, image, is_deleted, created_at, updated_at FROM categories_images
`

func (q *Queries) GetAllCategoryImages(ctx context.Context) ([]CategoriesImage, error) {
	rows, err := q.db.Query(ctx, getAllCategoryImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoriesImage{}
	for rows.Next() {
		var i CategoriesImage
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Image,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryImage = `-- name: GetCategoryImage :one
SELECT id, category_id, image, is_deleted, created_at, updated_at FROM categories_images WHERE id = $1
`

func (q *Queries) GetCategoryImage(ctx context.Context, id int32) (CategoriesImage, error) {
	row := q.db.QueryRow(ctx, getCategoryImage, id)
	var i CategoriesImage
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Image,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategoryImage = `-- name: UpdateCategoryImage :one
UPDATE categories_images
SET
    category_id = $2,
    image = $3
WHERE id = $1
RETURNING id
`

type UpdateCategoryImageParams struct {
	ID         int32       `json:"id"`
	CategoryID int32       `json:"category_id"`
	Image      pgtype.Text `json:"image"`
}

func (q *Queries) UpdateCategoryImage(ctx context.Context, arg UpdateCategoryImageParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateCategoryImage, arg.ID, arg.CategoryID, arg.Image)
	var id int32
	err := row.Scan(&id)
	return id, err
}
