// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (
    name,
    description
) VALUES (
    $1,
    $2
) RETURNING id
`

type CreateRoleParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (int32, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Description)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteRole = `-- name: DeleteRole :one
DELETE FROM roles WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteRole(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, deleteRole, id)
	err := row.Scan(&id)
	return id, err
}

const getAllRoles = `-- name: GetAllRoles :many
SELECT id, name, description, is_deleted, created_at, updated_at FROM roles
`

func (q *Queries) GetAllRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, getAllRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRole = `-- name: GetRole :one
SELECT id, name, description, is_deleted, created_at, updated_at FROM roles WHERE id = $1
`

func (q *Queries) GetRole(ctx context.Context, id int32) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET
    name = $2,
    description = $3
WHERE id = $1
RETURNING id
`

type UpdateRoleParams struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.ID, arg.Name, arg.Description)
	var id int32
	err := row.Scan(&id)
	return id, err
}
